### ISSUE TITLE
Problems with the include of axios

### ISSUE THREAD

**Issue by flx-rsc** [SAP-samples/ui5-typescript-tutorial#9]
Hello my problem has only marginally something to do with the example. 
The problem is this:
I am trying to include Axios as npm package.
i installed it with `npm install axios -D` and included it with `import axios from 'axios';`
This works also so far.
But the ui5-tooling-module delivers the node version and not the browser version. 

So my app crashes because require is not found.

What can i do?

thanks in advance

**Comment by petermuessig** [comment]
Hi @flx-rsc , which version of the `ui5-tooling-modules` do you consume? Did you update to the latest version?

**Comment by flx-rsc** [comment]
hi @petermuessig 
sorry for the late reply.
i had tested it with version 0.7.1. But unfortunately the error is still present after updating to 0.7.3.

**Comment by petermuessig** [comment]
Hi @flx-rsc ,
I did some rework of the `ui5-tooling-modules` and fixed an issue with the module resolution which is solved with `0.7.6`. Can you please verify? 
THX and BR, Peter

**Comment by petermuessig** [comment]
I just released `ui5-tooling-modules@0.7.7` - improves the module resolution and should now work properly

**Comment by flx-rsc** [comment]
Hi @petermuessig 
I have now tested it again with 0.7.7 unfortunately it still does not work. 

after the update i get the following errors:
```
ERR! server:custommiddleware:ui5-tooling-modules TypeError: Cannot read properties of undefined (reading 'type')
ERR! server:custommiddleware:ui5-tooling-modules     at Module.wrapMultipleReturns (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\class\Module.js:136:19)
ERR! server:custommiddleware:ui5-tooling-modules     at Module.prepare (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\class\Module.js:66:10)
ERR! server:custommiddleware:ui5-tooling-modules     at Module.convert (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\class\Module.js:53:12)
ERR! server:custommiddleware:ui5-tooling-modules     at module.exports (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\converter.js:14:12)
ERR! server:custommiddleware:ui5-tooling-modules     at Object.transform (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\ui5-tooling-modules\lib\rollup-plugin-amd-custom.js:19:22)
ERR! server:custommiddleware:ui5-tooling-modules     at C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\rollup\dist\shared\rollup.js:24220:40
ERR! server:custommiddleware:ui5-tooling-modules  Couldn't bundle axios: TypeError: Cannot read properties of undefined (reading 'type') TypeError: Cannot read properties of undefined (reading 'type')
ERR! server:custommiddleware:ui5-tooling-modules     at Module.wrapMultipleReturns (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\class\Module.js:136:19)
ERR! server:custommiddleware:ui5-tooling-modules     at Module.prepare (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\class\Module.js:66:10)
ERR! server:custommiddleware:ui5-tooling-modules     at Module.convert (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\class\Module.js:53:12)
ERR! server:custommiddleware:ui5-tooling-modules     at module.exports (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\converter.js:14:12)
ERR! server:custommiddleware:ui5-tooling-modules     at Object.transform (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\ui5-tooling-modules\lib\rollup-plugin-amd-custom.js:19:22)
ERR! server:custommiddleware:ui5-tooling-modules     at C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\rollup\dist\shared\rollup.js:24220:40 {
ERR! server:custommiddleware:ui5-tooling-modules   code: 'PLUGIN_ERROR',
ERR! server:custommiddleware:ui5-tooling-modules   plugin: 'commonjs--resolver',
ERR! server:custommiddleware:ui5-tooling-modules   hook: 'resolveId',
ERR! server:custommiddleware:ui5-tooling-modules   id: 'C:\\Users\\flx-rsc\\Documents\\com.myorg.myapp\\node_modules\\axios\\lib\\utils.js',
ERR! server:custommiddleware:ui5-tooling-modules   watchFiles: [
ERR! server:custommiddleware:ui5-tooling-modules     'C:\\Users\\flx-rsc\\Documents\\com.myorg.myapp\\node_modules\\axios\\index.js',
ERR! server:custommiddleware:ui5-tooling-modules     '\x00rollup-plugin-inject-process-env',
ERR! server:custommiddleware:ui5-tooling-modules     'C:\\Users\\flx-rsc\\Documents\\com.myorg.myapp\\node_modules\\axios\\lib\\axios.js',
ERR! server:custommiddleware:ui5-tooling-modules     'C:\\Users\\flx-rsc\\Documents\\com.myorg.myapp\\node_modules\\axios\\lib\\utils.js'
ERR! server:custommiddleware:ui5-tooling-modules   ]
ERR! server:custommiddleware:ui5-tooling-modules }
ERR! server:custommiddleware:ui5-tooling-modules TypeError: Cannot read properties of undefined (reading 'type')
ERR! server:custommiddleware:ui5-tooling-modules     at Module.wrapMultipleReturns (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\class\Module.js:136:19)
ERR! server:custommiddleware:ui5-tooling-modules     at Module.prepare (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\class\Module.js:66:10)
ERR! server:custommiddleware:ui5-tooling-modules     at Module.convert (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\class\Module.js:53:12)
ERR! server:custommiddleware:ui5-tooling-modules     at module.exports (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\converter.js:14:12)
ERR! server:custommiddleware:ui5-tooling-modules     at Object.transform (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\ui5-tooling-modules\lib\rollup-plugin-amd-custom.js:19:22)
ERR! server:custommiddleware:ui5-tooling-modules     at C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\rollup\dist\shared\rollup.js:24220:40
ERR! server:custommiddleware:ui5-tooling-modules  Couldn't bundle axios: TypeError: Cannot read properties of undefined (reading 'type') TypeError: Cannot read properties of undefined (reading 'type')
ERR! server:custommiddleware:ui5-tooling-modules     at Module.wrapMultipleReturns (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\class\Module.js:136:19)
ERR! server:custommiddleware:ui5-tooling-modules     at Module.prepare (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\class\Module.js:66:10)
ERR! server:custommiddleware:ui5-tooling-modules     at Module.convert (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\class\Module.js:53:12)
ERR! server:custommiddleware:ui5-tooling-modules     at module.exports (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\@buxlabs\amd-to-es6\src\converter.js:14:12)
ERR! server:custommiddleware:ui5-tooling-modules     at Object.transform (C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\ui5-tooling-modules\lib\rollup-plugin-amd-custom.js:19:22)
ERR! server:custommiddleware:ui5-tooling-modules     at C:\Users\flx-rsc\Documents\com.myorg.myapp\node_modules\rollup\dist\shared\rollup.js:24220:40 {
ERR! server:custommiddleware:ui5-tooling-modules   code: 'PLUGIN_ERROR',
ERR! server:custommiddleware:ui5-tooling-modules   plugin: 'commonjs--resolver',
ERR! server:custommiddleware:ui5-tooling-modules   hook: 'resolveId',
ERR! server:custommiddleware:ui5-tooling-modules   id: 'C:\\Users\\flx-rsc\\Documents\\com.myorg.myapp\\node_modules\\axios\\lib\\utils.js',
ERR! server:custommiddleware:ui5-tooling-modules   watchFiles: [
ERR! server:custommiddleware:ui5-tooling-modules     'C:\\Users\\flx-rsc\\Documents\\com.myorg.myapp\\node_modules\\axios\\index.js',
ERR! server:custommiddleware:ui5-tooling-modules     '\x00rollup-plugin-inject-process-env',
ERR! server:custommiddleware:ui5-tooling-modules     'C:\\Users\\flx-rsc\\Documents\\com.myorg.myapp\\node_modules\\axios\\lib\\axios.js',
ERR! server:custommiddleware:ui5-tooling-modules     'C:\\Users\\flx-rsc\\Documents\\com.myorg.myapp\\node_modules\\axios\\lib\\utils.js'
ERR! server:custommiddleware:ui5-tooling-modules   ]
ERR! server:custommiddleware:ui5-tooling-modules }
```

Thanks and br

**Comment by petermuessig** [comment]
I'll check it - there seems to be an issue parsing the module as AMD module... Being generic is always challenging - *sigh* 😅

**Comment by petermuessig** [comment]
Hi @flx-rsc, found the issue and fixed it. Releasing `ui5-tooling-modules:0.7.8` (should be available in some mins) - should really work now, I added axios also to my test cases! Please let me know if there are further issues with it...
